---
title: "R Markdown and Leaflet"
output: html_document
author: "Yves Morel SOKADJO"
date: "September 31, 2021"
---

Scope of the assignment
-----
Create a web page using R Markdown that features a map created with Leaflet.Host your webpage on either GitHub Pages, RPubs, or NeoCities. Your webpage must contain the date that you created the document, and it must contain a map created with Leaflet. We would love to see you show off your creativity!


September 31, 2021
----
```{r setup, echo=FALSE, include=F}
library(leaflet)
```

Modeling: Random Forest and Decision Trees
------
```{r, echo=F, message=F, warning=F}

In <- paste(sep = "<br/>",
                 "<b><a href='https://uac.bj/'>University of Abomey-Calavi</a></b>",
                 "Uac, Abomey Calavi, Benin",
                 "C8CV+H7 Godomey, Benin")

UAC= makeIcon(
iconUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fsocialprotection.org%2Fconnect%2Fstakeholders%2Funiversit%25C3%25A9-dabomey-calavi&psig=AOvVaw2Q9WbziQAJrDqTA-dyUWH9&ust=1641983971503000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCLCw9o3BqfUCFQAAAAAdAAAAABAD",
        iconWidth = 31 * 215/230, iconHeight = 31,
        iconAnchorX = 31 * 215/230/2, iconAnchorY = 16)


m = leaflet() %>% setView(lat = 6.4131143, lng = 2.3409617, zoom = 16) %>%
        addTiles() %>%
        addPopups(lat = 6.4131143, lng = 2.3409617, In, 
                  options = popupOptions(closeButton = FALSE)) %>%
        addMarkers(icon = UAC, lat = 6.4131143, lng = 2.3409617, 
                   popup = "Seng-Shi spent countless hours learning here!")
m
```

