---
title: "Regression Models Course Project"
output: pdf_document
---

Peer Review Portion
====
```{r setup, echo=FALSE, include=F}
library(dplyr)
library(ggplot2)
library(ggrepel)
library(scales)
library(hrbrthemes)
library(epiDisplay)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(finalfit)
library(arsenal)
library(caret)
library(kernlab)
library(nnet)
library(pROC)
library(rpart)
library(rpart.plot)
library(lattice) 
library(randomForest)

set.seed(3124)
trainingset <- read.csv("pml-training.csv", na.strings=c("NA","#DIV/0!", ""))
testingset <- read.csv("pml-testing.csv", na.strings=c("NA","#DIV/0!", ""))

trainingset<-trainingset[,colSums(is.na(trainingset)) == 0]
testingset <-testingset[,colSums(is.na(testingset)) == 0]


trainingset   <-trainingset[,-c(1:7)]
testingset <-testingset[,-c(1:7)]


traintrainset <- createDataPartition(y=trainingset$classe, p=0.75, list=FALSE)
TrainTrainingSet <- trainingset[traintrainset, ] 
TestTrainingSet <- trainingset[-traintrainset, ]

plot(TrainTrainingSet$classe, col="grey", main="Levels of classe in the TrainTrainingSet", xlab="classe", ylab="Frequency")

```

Random Forest
------
```{r, echo=TRUE, message=F, warning=F}
model1 <- randomForest(classe ~. , data=TrainTrainingSet, method="class")
prediction1 <- predict(model1, TestTrainingSet, type = "class")
confusionMatrix(prediction1, TestTrainingSet$classe)
```

Decision Tree
------
```{r, echo=TRUE, message=F, warning=F}
model2<- rpart(classe ~ ., data=TrainTrainingSet, method="class")
prediction2 <- predict(model2, TestTrainingSet, type = "class")
rpart.plot(model2, main="Classification Tree", extra=102, under=TRUE, faclen=0)

```

 
 The Test results on our TestTrainingSet data set is as follows:
```{r, echo=TRUE, message=F, warning=F}
confusionMatrix(prediction2, TestTrainingSet$classe)

```
 
 Model selection
--------

We could notice that Random Forest is better than Decision Trees. Accuracy for Random Forest model was 0.995 (95% CI: (0.993, 0.997)) compared to Decision Tree model with 0.739 (95% CI: (0.727, 0.752)). The Random Forests model is choosen. The expected out-of-sample error is estimated at 0.005, or 0.5%.

 
```{r, echo=TRUE, message=F, warning=F}
predictfinal <- predict(model1, testingset, type="class")
predictfinal
```


